server:
  port: 8081

  servlet:
    application-display-name: book-service

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/library
    username: root
    password: Hgpftd.lkhg;,gdvh99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update